name: core
description: "A new Flutter package project."
version: 0.0.1
homepage: "https"

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  dio: ^5.6.0
  equatable: ^2.0.5
  fast_rsa: ^3.6.4
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  wechat_assets_picker: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_utils: ^2.0.0

flutter:
  generate: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: lib/locales
  output_dir: lib/locales/generated
  output_locales: [en, vi, ko]
